### PR TITLE
Add smeagol plugin

### PR DESCRIPTION
**Pull request by schnatterer**
## Proposed changes

Add [scm-smeagol-plugin](https://github.com/schnatterer/scm-smeagol-plugin) for a  better integration of [smeagol](https://github.com/cloudogu/smeagol) into SCMM. I implemented it for the standalone version of smegaol, [smeagol-galore](https://github.com/schnatterer/smeagol-galore).
I'm almost embarrassed to open a PR for this plugin due to its lack of features. Right now all it does is add a link to `/smeagol` SCMM's navbar.

But then an official plugin is easier to install and makes it accessible to a broader audience.  Could even be a useful addition to the Cloudogu Ecosystem. There could be future useful additions like adding a `Wiki` item (similar to GitHub) to each repository's menu that contains a `.smeagol.yml`. Who knows, maybe someone from Cloudogu likes this idea and implements it.

image

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] PR is well described
- [x] Related issues linked to PR if existing and labels set - *there are none*
- [ ] Target branch is not master (in most cases develop should bet the target of choice) - *there's no develop :thinking:*
- [x] Code does not conflict with target branch
- [x] New code is covered with unit tests - *I presume code coverage does not apply to yaml changes. Does it?* 
- [x] CHANGELOG.md updated - *I presume that does not apply here?*
- [x] Definition of Done's fulfilled: [DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/definition-of-done.md) // [UI DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/ui-dod.md) - *I presume code coverage does not apply to yaml changes. Does it?* 
- [x] Documentation updated (only necessary for new features or changed behaviour)

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

### CODE REVIEW

**Comment by sdorra** [comment]
We have now an official [smeagol plugin](https://github.com/scm-manager/scm-smeagol-plugin). This plugin does not have a link in the header, but it provides a link to smeagol for each repository with an `.smeagol.yml` https://www.scm-manager.org/plugins/scm-smeagol-plugin/docs/1.0.x/en/overview/

**Comment by schnatterer** [comment]
Any chance we could add the link in the header as an option than can be enabled?
Wouldn't even need a UI for setting it. Setting it at startup would suffice for smeagol-galore.

**Comment by schnatterer** [comment]
I integrated the changes from my proposed scm-scmeagol-plugin into the official scm-smeagol plugin (schnatterer/scm-smeagol-plugin@a18be96b991db915b82789d9f790936c0d761211).

Just wondering which API to enrich in order to implement the predicate in UI for the primary nav option. Could you point me towards the right direction?

Would you be open for a PR that implements an optional primary nav link to smeagol?

**Comment by sdorra** [comment]
@schnatterer You can use an HalEnricher to enrich the index (`/api/v2`) with a link which points to the smeagol root. I think the simplest thing is to use the existing [IndexLinkEnricher](https://github.com/scm-manager/scm-smeagol-plugin/blob/develop/src/main/java/com/cloudogu/smeagol/IndexLinkEnricher.java) and add a `root` link to the `smeagol` array.

The links from the index can accessed by using the links prop from the `primary-navigation` endpoint.

**Comment by schnatterer** [comment]
Thanks @sdorra. I did my worst :smiling_imp:

**Pull request closed without merging**
