### PR TITLE
Migrated scm-htpasswd-plugin for scm-manager 2.x

### PR DESCRIPTION
**Pull request by ggrandes**
## Proposed changes

Migrated scm-passwd-plugin from scm-manager 1.x to 2.x. Based on scm-ldap-plugin. This will fix [issue 1961](https://github.com/scm-manager/scm-manager/issues/1961).

Plugin repository: https://github.com/ggrandes/scm-htpasswd-plugin

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [x] PR is well described and the description can be used as a commit message on squash
- [x] Related issues linked to PR if existing and labels set
- [x] New code is covered with unit tests
- [ ] New/updated ui components are tested inside the storybook (module ui-components only) 
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [ ] Feature has been tested with different permissions
- [x] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

### CODE REVIEW

**Comment by eheimbuch** [comment]
Hello Guillermo, 

thank you very much for your contribution. We would like to review your plugin and include it in our organization. After that we would publish it in the official plugin center. You will be the maintainer and you can request changes with pull request. If we can help you in any way, don't hesitate to ask.

Regards, Eduard

**Comment by eheimbuch** [comment]
Hey,

we reviewed your plugin and it works fine. There are only two things we are wondering about.

1. Could you use your own package name? It would clarify that this code was written by someone outside the SCM Team.
2. Would you provide documentation for this plugin? This is optional, but it could surely help out the community to understand the usage.

**Comment by ggrandes** [comment]
Yes. What you think about...
1. I could use ```org.javastack.scm.auth.htpasswd``` instead of ```sonia.scm.auth.htpasswd```. Suitable?
2. I could add not much literature, but something functional, and move some info from README.md to docs/.., ok?

**Comment by ggrandes** [comment]
(1) Package renamed. (2) Docs, tomorrow.

**Comment by ggrandes** [comment]
(2) Docs, done

**Comment by ggrandes** [comment]
Thanks @eheimbuch 👍

**Pull request merged**
